version: "3.4"

volumes:
  dev_sample_wagtail_data: {}

services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: sample_wagtail
      DATABASE_URL: postgres://postgres@127.0.01:5433/sample_wagtail
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    volumes:
      - dev_sample_wagtail_data:/var/lib/postgresql/data
